### ISSUE TITLE
Hangs when running fannkuch

### ISSUE THREAD

**Issue by kg** [WebAssembly/v8-native-prototype#26]
After running the ilwasm FannkuchRedux test ( https://gist.github.com/kg/e1ecdcc35c1468fd6074 ) through the latest rev of @binji's sexpr-wasm-prototype, executing the module's ```fannkuch``` method hangs forever in both debug and release builds of d8. I haven't figured out how to debug this (haven't gotten v8 gdbjit to work yet, traceback is useless).

**Comment by titzer** [comment]
I tried the file out; it's a bit out of date with the current load/store and ifs, but after some manual modifications, got it to load and can run the fannkuch() method. It doesn't hang anymore, but just returns undefined, and doesn't seem to print anything. I may have screwed up the loads or stores getting it to run.

Closing. Feel free to reopen with an updated WAST file if the bug is still there.
