### ISSUE TITLE
f32.neg spec tests failures w/ NaN

### ISSUE THREAD

**Issue by binji** [WebAssembly/v8-native-prototype#99]
The following spec tests fail:
```
(func $f32.neg (param $x f32) (result f32) (f32.neg (get_local $x)))
(export "f32.neg" $f32.neg)
...
(assert_return (invoke "f32.neg" (f32.const nan)) (f32.const -nan))
(assert_return (invoke "f32.neg" (f32.const -nan)) (f32.const nan))
(assert_return (invoke "f32.neg" (f32.const nan:0x0f1e2)) (f32.const -nan:0x0f1e2))
(assert_return (invoke "f32.neg" (f32.const -nan:0x0f1e2)) (f32.const nan:0x0f1e2))

(assert_return (invoke "f64.neg" (f64.const nan)) (f64.const -nan))
(assert_return (invoke "f64.neg" (f64.const -nan)) (f64.const nan))
(assert_return (invoke "f64.neg" (f64.const nan:0x0f1e27a6b)) (f64.const -nan:0x0f1e27a6b))
(assert_return (invoke "f64.neg" (f64.const -nan:0x0f1e27a6b)) (f64.const nan:0x0f1e27a6b))
```
I evaluate them in sexpr-wasm by generating something like the following:
```
(i32.eq (i32.reinterpret/f32 (call ...)) (i32.reinterpret/f32 (f32.const ...)))
```

**Comment by gahaas** [comment]
In my opinion the spec tests do not match the IEEE 754 specification here. The IEEE spec says:

"Propagation of the diagnostic information requires that information
contained in the NaNs be preserved through arithmetic operations and
floating-point format conversions."

I think we should change the spec test here.

**Comment by binji** [comment]
Could you file a bug in the spec repo then?

**Comment by sunfishcode** [comment]
The spec, IEEE 754, and these tests all agree that the payload bits of a NaN are preserved by floating-point `neg`. `assert_return` is not part of the spec, but it is expected to do a bitwise comparison, as in @binji's example above.

**Comment by gahaas** [comment]
I think I expressed myself imprecisely. I agree that we should do bitwise comparison, especially because it's necessary for cases like +0.0 and -0.0. What I am questioning here is the result of f32.neg(NaN) and f64.neg(NaN). According to the sentence I cited above, f32.neg and f64.neg should leave the sign bit of NaN untouched, because these are arithmetic operations and the sign bit is part of the diagnostic information that the standard requires to preserve. Additionally, negation typically corresponds to a multiplication with -1, and NaN * -1 = NaN, and not -NaN. 

In my opinion the test should therefore be

(assert_return (invoke "f64.neg" (f64.const nan)) (f64.const nan))

**Comment by sunfishcode** [comment]
Neg is defined along with abs and copysign in a special section in IEEE 754, "Quiet-computational operations", which says of these operators, "[...] they only affect the sign bit. The operations treat floating-point numbers and NaNs alike [...]", and goes on to define the operators as purely bitwise operations manipulating sign bits.

**Comment by gahaas** [comment]
Ah, sorry that I missed that one. Thanks for pointing it out.

**Comment by gahaas** [comment]
I changed the implementation and the tests pass now.
